<?php

namespace Modules\Customer\Database\Seeders;

use Illuminate\Database\Seeder;

class CustomerUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->whereBetween('id', [10249, 10338])->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 10249,
                'name' => 'budi-sihombing',
                'email' => 'budi-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$XfNIvI5BubITupvf6tofOOgdvzPxdhUcxxDNzGBrq2d5PqXLa9enq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            1 => 
            array (
                'id' => 10250,
                'name' => 'umi-wibowo',
                'email' => 'umi-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dSNBTwYfD8nmqttVd.criuE5X05tfY7PUO01LV.Fkdpm3LIXc/ZKm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            2 => 
            array (
                'id' => 10251,
                'name' => 'eko-hutapea',
                'email' => 'eko-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VgVWAoC1QScv6KSB1hgWwe.W3tE8oRcRQztZZ0HofDvfLOnI6Lobe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:25',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            3 => 
            array (
                'id' => 10252,
                'name' => 'tono-tambunan',
                'email' => 'tono-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$z2erBKPvG8i0PJQhqIdA0OjgOaPn7ybEXxNRkx2MiC/KFfpzuer/y',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            4 => 
            array (
                'id' => 10253,
                'name' => 'agus-sihombing',
                'email' => 'agus-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$rc45ihLAHumBx.KoNxImUe0JnrfPT9gU6OUv.4LfUXGmVF56izXC6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:26',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            5 => 
            array (
                'id' => 10254,
                'name' => 'gita-sinaga',
                'email' => 'gita-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$.niUq3lfrKONoxXGQ9J0hu7Jlzcq0ZVzGiyjPbYnc5LAnrglghrMu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            6 => 
            array (
                'id' => 10255,
                'name' => 'gita-tambunan',
                'email' => 'gita-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$kCvtA/yltj5Vd.cpOyvRGOjUESkPVAYJLI8mbaVIRLMxJyWfdtrsa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            7 => 
            array (
                'id' => 10256,
                'name' => 'umi-nasution',
                'email' => 'umi-nasution@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$t77lCeKjlL5AvPshAQrvhO3/Gwfopuy3LQZiRCVON04zEShbu2JLS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:27',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            8 => 
            array (
                'id' => 10257,
                'name' => 'dewi-tambunan',
                'email' => 'dewi-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$24iT3Osq3n9a6nkxqpxgPuDV08d.9JN2VH7Zx2.z98SSlhsllWhnC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            9 => 
            array (
                'id' => 10258,
                'name' => 'slamet-hidayat',
                'email' => 'slamet-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/2vXedsWB4FTYVhgnF8tIO9Gq86RjKeJWScKV1nr3KSXkTLO9nidq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            10 => 
            array (
                'id' => 10259,
                'name' => 'kadek-lestari',
                'email' => 'kadek-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$ChPDe2JakTeX0HJHKTfQVOcbaGztTY9Oi3IlnQFC5kAQXD/qWRhpO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:28',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            11 => 
            array (
                'id' => 10260,
                'name' => 'dewi-rahayu',
                'email' => 'dewi-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lxxIAemYyiLGtcegX1hJj.M1txYNtWc75mLeqXanNLn4UIsBirvGS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            12 => 
            array (
                'id' => 10261,
                'name' => 'andi-ramadhan',
                'email' => 'andi-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$dLTovZWVvXmJJL6oAP6dbuvDdAE2db0kjW2DugDQnM7wkSj8Qv6Ty',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            13 => 
            array (
                'id' => 10262,
                'name' => 'bambang-saputra',
                'email' => 'bambang-saputra@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$fjIk5DsY5vNddslGWI6e.O8cONw2xZQ4qzXt7Hw7eWQC2dmE4TROm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:29',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            14 => 
            array (
                'id' => 10263,
                'name' => 'fajar-hutapea',
                'email' => 'fajar-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$OYqmtHKVLGW4u2GwTlK8XuZS5rqtEEIQAWZC/G2ZxAsHgbzzFvAYK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            15 => 
            array (
                'id' => 10264,
                'name' => 'fajar-sihombing',
                'email' => 'fajar-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zw74O2.9AHM70pBaMMtRded0kGOt21rBK0GSPeEJq9w/aYv9X9ymq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            16 => 
            array (
                'id' => 10265,
                'name' => 'endah-susanto',
                'email' => 'endah-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$osmkLNJPmf8W5BZkzdRAeOEv42DmIvFFnNCJgafZHBg4V91qD6j22',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:30',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            17 => 
            array (
                'id' => 10266,
                'name' => 'rina-tambunan',
                'email' => 'rina-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$DsOwDfjbRFo8rOWx0j1ToOR/SUblLFXAFCtIcqFANMAk0v/QqyT6a',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            18 => 
            array (
                'id' => 10267,
                'name' => 'wahyu-silitonga',
                'email' => 'wahyu-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$4uTnEtdRAFBik6P8i/M05OR82drEmIknumi/68uKZEt4Mr/mjs.hm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:31',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            19 => 
            array (
                'id' => 10268,
                'name' => 'lina-setiawan',
                'email' => 'lina-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w0LlCg.BkL1xsYeUQlaXmeBRGe1MbDJIQmSZXy7ZcJdhASvL/H2BK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:32',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            20 => 
            array (
                'id' => 10269,
                'name' => 'gita-anggraini',
                'email' => 'gita-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$MjfGMSNtewC2yQsAIfGksunvQmRpxozAJjBTBW..zJodZZDz44OI2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            21 => 
            array (
                'id' => 10270,
                'name' => 'dewi-pratama',
                'email' => 'dewi-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$8VUo5XkkiJ954WmvoaCGU.HWZBTT/mxMmXtDgolQKL/GT7wGl0v2W',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            22 => 
            array (
                'id' => 10271,
                'name' => 'andi-simanjuntak',
                'email' => 'andi-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$nSnaK1hQoFI/MNq88wGYcOvYAHejk1FwRqZqBGPJ6x2VTemu60bqa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:33',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            23 => 
            array (
                'id' => 10272,
                'name' => 'wahyu-santoso',
                'email' => 'wahyu-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$UfouZG0OlffkcPLS//XYBenIxw6IgMkzwqFWhjXTkPyNgS7syapFq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            24 => 
            array (
                'id' => 10273,
                'name' => 'made-anggraini',
                'email' => 'made-anggraini@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w8htDHSZN4P5DGhoHVeXU.n1K28QZRU57Qaj2NjfezT.nKiaas36m',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            25 => 
            array (
                'id' => 10274,
                'name' => 'sari-maulana',
                'email' => 'sari-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$78VydxhaX/iYv9wrAaJ7JuRJVnTviYcWdjmzDrKu4J4Hnls/Gjnje',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            26 => 
            array (
                'id' => 10275,
                'name' => 'slamet-tambunan',
                'email' => 'slamet-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hDjBKZKMIBh82l7rFfw91uH5cbnrZfY.4qC1AOSik9SOsQbqdd31e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:34',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            27 => 
            array (
                'id' => 10276,
                'name' => 'andi-sinaga',
                'email' => 'andi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SIF0c1KXgs6PSH8lrq8sEOp52AAUEaZ4Avn1rwjlpW1T58hiZjGHm',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            28 => 
            array (
                'id' => 10277,
                'name' => 'umi-utami',
                'email' => 'umi-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QBAmJz1MqjFUGNde1063Ye/uH9DRXmwkiawwMzyot71.mRDrYYIvS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:35',
                'updated_at' => '2026-09-07 13:53:56',
            ),
            29 => 
            array (
                'id' => 10278,
                'name' => 'slamet-halim',
                'email' => 'slamet-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$pA3Y4RhycRPu1qBYeioE.esgxUUdLZQCgKaSdEqa/klRKYF.cgv5C',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            30 => 
            array (
                'id' => 10279,
                'name' => 'eko-utami',
                'email' => 'eko-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$enXze4mW1zgFFZrsJ.pcO.25QSNT0C2kbZCp5aVkU9xMvG8QmTwJe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:36',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            31 => 
            array (
                'id' => 10280,
                'name' => 'cahyo-tambunan',
                'email' => 'cahyo-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$skyl/pIPJ7PyTxd696Y3R.CYdCPpcxUtui3gi8TiW7TDoNdxJTRgC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            32 => 
            array (
                'id' => 10281,
                'name' => 'eko-sihombing',
                'email' => 'eko-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$04OVNh9K.83CNmbbOqBQ4.0G8PtkAlc9abqHX2nXesytU3Tam6o1e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:37',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            33 => 
            array (
                'id' => 10282,
                'name' => 'umi-silitonga',
                'email' => 'umi-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$xoI73LTF3Mq19Woic5KLauHGI0Y.67K0Qn7Wa9wUqq33JFIrnXU2.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            34 => 
            array (
                'id' => 10283,
                'name' => 'tono-sihombing',
                'email' => 'tono-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$UVNmIPc3btKlk570GHWF2urRRRlMFi7kx/IovDcDRqv87wAA8.tdK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:38',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            35 => 
            array (
                'id' => 10284,
                'name' => 'zainal-nugroho',
                'email' => 'zainal-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$I8JZpDS5fkUwimDiLnXXWuap/AB0bZ0FvQx/X1hq2U1jTBaxPpVgG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            36 => 
            array (
                'id' => 10285,
                'name' => 'budi-rahayu',
                'email' => 'budi-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$w82r7QXZvx5IEtWA4nm9xO8TWyHQHEZos9zYWgw./D.MdZJF.9/DK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            37 => 
            array (
                'id' => 10286,
                'name' => 'dedi-lestari',
                'email' => 'dedi-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3vSUPOmndoZhJ/SCgZPIkeUG25koQkzYs3l65OPhBKl5hstX/FKmy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:39',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            38 => 
            array (
                'id' => 10287,
                'name' => 'endah-firmansyah',
                'email' => 'endah-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$tV0SFf664cJVj6ZRDFmahOLX5qNniLRFXPGoP4d7W/5ISx0rpjtNS',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            39 => 
            array (
                'id' => 10288,
                'name' => 'yanti-hidayat',
                'email' => 'yanti-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/a39I9y/z/gtNsB7/7m33uV0Sz4Y6v6BAVb2v0U986zMjlrdxNnDi',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            40 => 
            array (
                'id' => 10289,
                'name' => 'cahyo-siahaan',
                'email' => 'cahyo-siahaan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aqSj5abwmrwk3NJFRKe7OuArvIACXxHMxi2XIwmqy/quM0bT63rYe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:40',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            41 => 
            array (
                'id' => 10290,
                'name' => 'kadek-siregar',
                'email' => 'kadek-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KXrWc1KfCGBGrlJFRK3m.uAKwP6VuW7/FZxY2LbfRwoSWn3eCFdl6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            42 => 
            array (
                'id' => 10291,
                'name' => 'eko-pratama',
                'email' => 'eko-pratama@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$jJuAAQatXa/ARGMDpTRmpORkGrNJTduumhcbCsRlfSb5k0WBQRwgu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:41',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            43 => 
            array (
                'id' => 10292,
                'name' => 'rina-wibowo',
                'email' => 'rina-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Y2qrMIWUBCBjjVWFZJE2hu2L3xrSDKDWJSkVoRMBZdNuwCIaq5Jg6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            44 => 
            array (
                'id' => 10293,
                'name' => 'made-purba',
                'email' => 'made-purba@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$CYyghEFVNDOcwEgYer3T0.ogSYgRo2kfNe1d8Hmd4b//4yRJ85A6S',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            45 => 
            array (
                'id' => 10294,
                'name' => 'andi-firmansyah',
                'email' => 'andi-firmansyah@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lyY5Sb0BiavFxV0EiXkReuCFtaWjuOKbYaEp1wXaT0bKCdb..JV8O',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:42',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            46 => 
            array (
                'id' => 10295,
                'name' => 'endah-rahayu',
                'email' => 'endah-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$utapI1e.7wfDRcxP/Xg6eutXMc8tOy342QVBZIlsSJ5btgqExSJc6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            47 => 
            array (
                'id' => 10296,
                'name' => 'nina-nugroho',
                'email' => 'nina-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3PmXpdjb2xVdtp3TRAV8HenWjq1tLBTOhKpf8a4cry7urgnxtjnn6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            48 => 
            array (
                'id' => 10297,
                'name' => 'hadi-halim',
                'email' => 'hadi-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$KmM1JYW3fxQ7wN2TizcBcuU9g1sthabiR7bqbox/TpnJIXDHEomQe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            49 => 
            array (
                'id' => 10298,
                'name' => 'joko-tambunan',
                'email' => 'joko-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$eq7H7BjWBUHfoIwjsxv0/u/.2eX9FTgiPBCQnMDjNJ968l0MlY5yq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:43',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            50 => 
            array (
                'id' => 10299,
                'name' => 'budi-sinaga',
                'email' => 'budi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$AIwCeN13cBKD62qpGcIgiuGEvKZmWjUKQnWxFOXo6uS1ycfb0gQCu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            51 => 
            array (
                'id' => 10300,
                'name' => 'agus-hidayat',
                'email' => 'agus-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2y.BeaeQugKHN37bjFPjwuKCbtoihv.YUSVrR4dUGSPhBJSxGq036',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            52 => 
            array (
                'id' => 10301,
                'name' => 'eko-susanto',
                'email' => 'eko-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$W2fSrsEuGgz20QuWfCYE.ubudIGN4znvXgNz3tQyBIZ2.v5E4W17e',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:44',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            53 => 
            array (
                'id' => 10302,
                'name' => 'bambang-rahayu',
                'email' => 'bambang-rahayu@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lnEanAAI2.5vhWWQ/zxK2.6nsv6V8Nq0y7xgi.8j2F1lkTx3mGO8S',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:45',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            54 => 
            array (
                'id' => 10303,
                'name' => 'adi-purba',
                'email' => 'adi-purba@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ag0jftidkbuaJGgCO/iA/.W144zknh/gAjMcbnpW3Vv0HRktM3AGO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            55 => 
            array (
                'id' => 10304,
                'name' => 'ratna-sinaga',
                'email' => 'ratna-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$2Yty.T0W4DG7exXUQ6iFJO3/wcw/S6M5.sWc113q1n4NbEuduaA7i',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            56 => 
            array (
                'id' => 10305,
                'name' => 'lina-tambunan',
                'email' => 'lina-tambunan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$HgMDHS8MYS4yucxtVD8FaO0D5dr2oH2DrL9E/0b77BjhMJiXcNjKy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:46',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            57 => 
            array (
                'id' => 10306,
                'name' => 'budi-lestari',
                'email' => 'budi-lestari@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Yz3dltB0.rEE0Zqo7E60uu4KVDDD2x8e0rg6t524bSFDGCb1/Qf9G',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            58 => 
            array (
                'id' => 10307,
                'name' => 'made-setiawan',
                'email' => 'made-setiawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$SFVPbSWqNHF03C/oYekW4uATT2IkXuriTQur74nCQGva7KNISkEGe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            59 => 
            array (
                'id' => 10308,
                'name' => 'umi-sinaga',
                'email' => 'umi-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$QILCUBI6E8BqQHC512.Ufem55gBarxhzd42D3Js2t6UbxeFMSmGy6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:47',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            60 => 
            array (
                'id' => 10309,
                'name' => 'lina-sinaga',
                'email' => 'lina-sinaga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$/Feu0jyj2sLBEHFBBU7PL.dbd5fSAYmoGKhwGDdJj2or/JsqxheIu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            61 => 
            array (
                'id' => 10310,
                'name' => 'dwi-simanjuntak',
                'email' => 'dwi-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$hI2Im.Oe9s3GD62KyfGGgu90cNRkYxld.LBwg4WgGrVqhGZw/Pyby',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:48',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            62 => 
            array (
                'id' => 10311,
                'name' => 'made-utami',
                'email' => 'made-utami@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$yjONUvOvtt6FGiYtbWFTV.zck9X9cA6ZUzy90mrBz2FbN2Qnm6diO',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            63 => 
            array (
                'id' => 10312,
                'name' => 'andi-santoso',
                'email' => 'andi-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$3PLoEwt7PshkQK2jO9VCOuDezR.T2KsNEaon.F2g1cfKTAhsxNK12',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            64 => 
            array (
                'id' => 10313,
                'name' => 'fajar-wibowo',
                'email' => 'fajar-wibowo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$yvYPjXqDs7F6UPy55/g4POp2F2tBOTH3qWymGVLWxGEBx05AXt2f2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:49',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            65 => 
            array (
                'id' => 10314,
                'name' => 'putra-halim',
                'email' => 'putra-halim@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qltwHqceDk7VI.Fp9tE1UePNBoGvw01jfNQSWjtrrqcarkT.SmqHK',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            66 => 
            array (
                'id' => 10315,
                'name' => 'zainal-susanto',
                'email' => 'zainal-susanto@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$aaQnz9Vo2iB8okFlvJQudO94AiNU/e60Z1KkFvtfKQvRtyjKGq2u.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            67 => 
            array (
                'id' => 10316,
                'name' => 'yanti-silitonga',
                'email' => 'yanti-silitonga@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Gb2hSZzsrQ2TorStdqctBOyeUu197Rw1bHGv6BCupJwf6pEfOZdoC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:50',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            68 => 
            array (
                'id' => 10317,
                'name' => 'yanti-simanjuntak',
                'email' => 'yanti-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$unZHuSERlGeMyGM76J0VDOgrfKFduuVSqyXPCwEu1IuAbuHxJ0eYy',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            69 => 
            array (
                'id' => 10318,
                'name' => 'budi-maulana',
                'email' => 'budi-maulana@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$VAIWcGdleJ5D.X62bIVcR.dow8CEPhTDlF9jiyx1o05POto9XUcYG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            70 => 
            array (
                'id' => 10319,
                'name' => 'wahyu-siregar',
                'email' => 'wahyu-siregar@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$kmSO.fdm51AORORzNdx5vu6Wor/p.2BOJ8y/pycEPHKiH8PZd7YO2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            71 => 
            array (
                'id' => 10320,
                'name' => 'adi-gunawan',
                'email' => 'adi-gunawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$h5sL3Fqi4tsUrdgIH8XFHODQKGuz4AFFhGJX2sGgI5wIqAuBF6tnq',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:51',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            72 => 
            array (
                'id' => 10321,
                'name' => 'bambang-simanjuntak',
                'email' => 'bambang-simanjuntak@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$F5EPf1Fy7z01UgmbzYUPQ.ffLLMGVXuWIPKqqxXiboAExrh6OUmy.',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            73 => 
            array (
                'id' => 10322,
                'name' => 'rina-manullang',
                'email' => 'rina-manullang@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$Ur2uGAxD5Q/SX9RjeAGWzOLn.qin1td7BclXaN3B5lXqTb/esD1WG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            74 => 
            array (
                'id' => 10323,
                'name' => 'slamet-ramadhan',
                'email' => 'slamet-ramadhan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$EYv1somPIYbFVThaxBec8.hRjZ28z5S/dIeFBVZ1XgY.6/NlQCXG6',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:52',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            75 => 
            array (
                'id' => 10324,
                'name' => 'budi-hidayat',
                'email' => 'budi-hidayat@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$lDY5DYrRYJzqz/k05.oeNue6ks8XUBbZ9/Y/VwPI7ixC.LDXvMfGu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            76 => 
            array (
                'id' => 10325,
                'name' => 'gita-sihombing',
                'email' => 'gita-sihombing@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$zHNfSxhW/RjqlwvPknvI7ON584h3ZeXTgnrPjnsJi10Bsv2qcSqNu',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            77 => 
            array (
                'id' => 10326,
                'name' => 'joko-nugroho',
                'email' => 'joko-nugroho@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$f.vCpdaPNleWgzB6GOUW4uqYkkcokqpN1dN2V04sq7qtJNJMj/bh2',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            78 => 
            array (
                'id' => 10327,
                'name' => 'eko-wijaya',
                'email' => 'eko-wijaya@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$qTzbTrzyHif1Edr5nk8IH.N12TYYNdL0jzlFReUViptD6DPD5Wjoa',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:53',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            79 => 
            array (
                'id' => 10328,
                'name' => 'umi-hutapea',
                'email' => 'umi-hutapea@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$mdztALDZqNpKCogmm58.iemx0ZaEG74MvUgRCJKjTUjiM/X885kjG',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            80 => 
            array (
                'id' => 10329,
                'name' => 'agus-santoso',
                'email' => 'agus-santoso@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$YIgv8dSJ3NPEG7L2SihyDuEg2r3PB2ONpwwG.svM6wWN5Vg4Q9DFe',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:54',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            81 => 
            array (
                'id' => 10330,
                'name' => 'rudi-hartono',
                'email' => 'rudi-hartono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:57',
                'updated_at' => '2026-09-07 13:53:57',
            ),
            82 => 
            array (
                'id' => 10331,
                'name' => 'susi-susanti',
                'email' => 'susi-susanti@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            83 => 
            array (
                'id' => 10332,
                'name' => 'teguh-prasetyo',
                'email' => 'teguh-prasetyo@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            84 => 
            array (
                'id' => 10333,
                'name' => 'dian-pertiwi',
                'email' => 'dian-pertiwi@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            85 => 
            array (
                'id' => 10334,
                'name' => 'hendra-gunawan',
                'email' => 'hendra-gunawan@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            86 => 
            array (
                'id' => 10335,
                'name' => 'ratih-kumala',
                'email' => 'ratih-kumala@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            87 => 
            array (
                'id' => 10336,
                'name' => 'rina-marlina',
                'email' => 'rina-marlina@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            88 => 
            array (
                'id' => 10337,
                'name' => 'bowo-laksono',
                'email' => 'bowo-laksono@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
            89 => 
            array (
                'id' => 10338,
                'name' => 'sri-wahyuni',
                'email' => 'sri-wahyuni@wasnaker.lan',
                'email_verified_at' => NULL,
                'password' => '$2y$12$1qnfw0xgw.ng6j8dANVXIO5CnHNo0.bVIN9oRdZ/gQAsJUiwAf4QC',
                'is_active' => 1,
                'avatar' => NULL,
                'remember_token' => NULL,
                'created_at' => '2026-09-07 13:53:58',
                'updated_at' => '2026-09-07 13:53:58',
            ),
        ));

        // Set AUTO_INCREMENT setelah module Customer selesai:
        // user baru via app mulai dari 80000, tidak pernah masuk range statis modul lain.
        \DB::statement('ALTER TABLE users AUTO_INCREMENT = 80000');
    }
}